name: CI
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: |
          yarn install
          yarn build
          yarn lerna bootstrap
          yarn lint
          yarn test
      - name: Coveralls
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info # optional (default value)

  py:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('packages/py-ab-testing/*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
      - name: Install dependencies
        working-directory: ./packages/py-ab-testing
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Lint with flake8
        working-directory: ./packages/py-ab-testing
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        working-directory: ./packages/py-ab-testing
        run: |
          pip install -r requirements.txt
          pip install -e .
          pytest \
            --cov-config=.coveragerc \
            --cov=ABTesting \
            --cov-branch \
            --cov-report=html:cov.html \
            --cov-report=term-missing:skip-covered \
            tests
      - name: Coveralls
        # if: ${{ github.ref == 'refs/heads/master' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true
        run: |
          coveralls

  finish_coveralls:
    runs-on: ubuntu-latest
    needs:
      - js
      - py
    steps:
      - name: Coveralls
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          parallel-finished: true
